(()=>{'use strict';
const COACH='refaey11@icloud.com';
const SUPABASE_URL='https://zkymvovbpfrwjyfwylbq.supabase.co';
const SUPABASE_KEY='sb_publishable_9SgCU4D-48kgotUdi79gfQ_NaouEXbO';
const $=s=>document.querySelector(s),norm=e=>String(e||'').trim().toLowerCase();
function sb(){if(window.supabaseClient?.auth)return window.supabaseClient;if(window.supabase?.auth)return window.supabase;if(window.supabase?.createClient){window.supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return window.supabaseClient}return null}
function clearLocal(){['rafProfile','rafActiveClient','rafActiveClientId'].forEach(k=>localStorage.removeItem(k));}
function showGate(){let g=$('#raf-supa-auth');if(g){g.style.display='flex';return}g=document.createElement('div');g.id='raf-supa-auth';g.innerHTML='<div><form id="raf-supa-form"><h2>RAF Coaching</h2><p id="raf-auth-sub">Sign in to continue</p><input id="raf-auth-email" type="email" autocomplete="email" placeholder="Email" required><input id="raf-auth-password" type="password" autocomplete="current-password" placeholder="Password" required><button type="submit" data-mode="signin">Sign In</button><button type="button" id="raf-forgot">Forgot password?</button><div id="raf-auth-msg" role="status"></div></form></div>';document.body.appendChild(g);$('#raf-supa-form').addEventListener('submit',signin);$('#raf-forgot').addEventListener('click',forgot)}
function hideGate(){const g=$('#raf-supa-auth');if(g)g.style.display='none'}
function authActions(){const host=$('#raf-auth-actions');if(!host)return;host.innerHTML='<button id="raf-logout" type="button" style="width:100%;margin:16px 0;padding:11px 14px;border:1px solid #d4e2cf;border-radius:12px;background:#fff;color:#315a2c;font-weight:750;cursor:pointer">Log out</button>';$('#raf-logout').onclick=()=>window.RAF_AUTH_V3.logout()}
async function signin(e){e.preventDefault();const s=sb(),msg=$('#raf-auth-msg');if(!s){msg.textContent='Authentication service failed to load. Refresh and try again.';return}msg.textContent='Signing in…';const email=norm($('#raf-auth-email').value),password=$('#raf-auth-password').value;const r=await s.auth.signInWithPassword({email,password});if(r.error){msg.textContent=r.error.message;return}await refresh(r.data.user)}
async function forgot(){const s=sb(),email=norm($('#raf-auth-email').value),msg=$('#raf-auth-msg');if(!s||!email){msg.textContent='Enter your email first.';return}const r=await s.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg.textContent=r.error?r.error.message:'Password reset email sent.'}
async function refresh(user){if(!user){clearLocal();document.body.dataset.rafRole='guest';showGate();const a=$('#raf-auth-actions');if(a)a.innerHTML='';return null}const email=norm(user.email),role=email===COACH?'coach':'client';window.RAF_AUTH_ROLE={authenticated:true,email,role,isCoach:role==='coach',userId:user.id};hideGate();document.body.dataset.rafRole=role;authActions();document.dispatchEvent(new CustomEvent('raf-auth-ready',{detail:window.RAF_AUTH_ROLE}));window.RAF_AUTH?.enforce?.();return window.RAF_AUTH_ROLE}
async function boot(){const s=sb();if(!s){showGate();return}const r=await s.auth.getSession();await refresh(r.data?.session?.user||null);s.auth.onAuthStateChange((_e,session)=>setTimeout(()=>refresh(session?.user||null),0))}
window.RAF_AUTH_V3={boot,refresh,logout:async()=>{const s=sb();if(s)await s.auth.signOut();clearLocal();showGate();location.hash='dashboard';location.reload()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();