(()=>{'use strict';
const COACH='refaey11@icloud.com';const SUPABASE_URL='https://zkymvovbpfrwjyfwylbq.supabase.co';const SUPABASE_KEY='sb_publishable_9SgCU4D-48kgotUdi79gfQ_NaouEXbO';
const $=s=>document.querySelector(s),norm=e=>String(e||'').trim().toLowerCase();let client,lastUserId=null;
function sb(){if(client)return client;if(window.supabaseClient?.auth)return client=window.supabaseClient;if(window.supabase?.auth)return client=window.supabase;if(window.supabase?.createClient)return client=window.supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return null}
function clearLocal(){['rafProfile','rafActiveClient','rafActiveClientId'].forEach(k=>localStorage.removeItem(k));lastUserId=null}
function showGate(){let g=$('#raf-supa-auth');if(g){g.style.display='flex';return}g=document.createElement('div');g.id='raf-supa-auth';g.innerHTML='<div><form id="raf-supa-form"><h2>RAF Coaching</h2><p id="raf-auth-sub">Welcome back</p><div id="raf-signin-fields"><input id="raf-auth-email" type="email" autocomplete="email" placeholder="Email" required><input id="raf-auth-password" type="password" autocomplete="current-password" placeholder="Password" required></div><div id="raf-signup-fields" style="display:none"><input id="raf-auth-name" type="text" autocomplete="name" placeholder="Full name"><input id="raf-auth-password2" type="password" autocomplete="new-password" placeholder="Confirm password"></div><button type="submit" id="raf-submit" data-mode="signin">Sign In</button><button type="button" id="raf-toggle">Create account</button><button type="button" id="raf-forgot">Forgot password?</button><div id="raf-auth-msg" role="status"></div></form></div>';document.body.appendChild(g);$('#raf-supa-form').addEventListener('submit',submit);$('#raf-toggle').addEventListener('click',toggle);$('#raf-forgot').addEventListener('click',forgot)}
function toggle(){const signup=$('#raf-submit').dataset.mode==='signin';$('#raf-submit').dataset.mode=signup?'signup':'signin';$('#raf-submit').textContent=signup?'Create account':'Sign In';$('#raf-toggle').textContent=signup?'Back to sign in':'Create account';$('#raf-signin-fields').style.display=signup?'none':'';$('#raf-signup-fields').style.display=signup?'':'none';$('#raf-auth-sub').textContent=signup?'Create your client account':'Welcome back';$('#raf-forgot').style.display=signup?'none':'';$('#raf-auth-msg').textContent='';$('#raf-auth-password2').required=signup}
function finishButton(){const b=$('#raf-submit');if(b){b.disabled=false;b.removeAttribute('aria-busy')}}
async function restSignIn(email,password){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password}),signal:ctl.signal,cache:'no-store'});let data=null;try{data=await r.json()}catch(_){}if(!r.ok)return{error:new Error(data?.msg||data?.message||data?.error_description||'Invalid login credentials')};if(!data?.access_token||!data?.refresh_token||!data?.user)return{error:new Error('Authentication response was incomplete. Please try again.')};return{data}}catch(err){return{error:err?.name==='AbortError'?new Error('The login server is taking too long to respond. Please try again.'):err}}finally{clearTimeout(timer)}}
async function submit(e){e.preventDefault();const s=sb(),msg=$('#raf-auth-msg'),btn=$('#raf-submit');if(!s){msg.textContent='Authentication service failed to load. Refresh and try again.';return}const mode=btn.dataset.mode,email=norm($('#raf-auth-email').value),password=$('#raf-auth-password').value;btn.disabled=true;btn.setAttribute('aria-busy','true');msg.textContent=mode==='signup'?'Creating account…':'Signing in…';try{if(mode==='signup'){if(email===COACH){msg.textContent='This email is reserved for the coach.';return}const p2=$('#raf-auth-password2').value;if(password.length<6){msg.textContent='Password must be at least 6 characters.';return}if(password!==p2){msg.textContent='Passwords do not match.';return}const name=String($('#raf-auth-name').value||'').trim(),r=await s.auth.signUp({email,password,options:{data:{full_name:name||'Client'}}});if(r.error){msg.textContent=r.error.message;return}if(r.data?.session?.user)applyUser(r.data.session.user);else{msg.textContent='Account created. Check your email to confirm, then sign in.';toggle()}}else{const r=await restSignIn(email,password);if(r.error){msg.textContent=r.error.message;return}const u=r.data.user,session={access_token:r.data.access_token,refresh_token:r.data.refresh_token,expires_in:r.data.expires_in,expires_at:r.data.expires_at,token_type:r.data.token_type,user:u};applyUser(u);hideGate();msg.textContent='';setTimeout(()=>s.auth.setSession(session).catch(()=>{}),0)}}catch(err){msg.textContent=err?.message||'Sign in failed. Please try again.'}finally{finishButton()}}
async function forgot(){const s=sb(),email=norm($('#raf-auth-email').value),msg=$('#raf-auth-msg');if(!s||!email){msg.textContent='Enter your email first.';return}const r=await s.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg.textContent=r.error?r.error.message:'Password reset email sent.'}
function authActions(){const host=$('#raf-auth-actions');if(!host)return;host.innerHTML='<button id="raf-logout" type="button" class="raf-logout">Log out</button>';$('#raf-logout').onclick=()=>window.RAF_AUTH_V3.logout()}
function applyUser(user){if(!user){if(lastUserId===null&&document.body.dataset.rafRole==='guest')return null;lastUserId=null;clearLocal();document.body.dataset.rafRole='guest';showGate();const a=$('#raf-auth-actions');if(a)a.innerHTML='';return null}if(lastUserId===user.id&&window.RAF_AUTH_ROLE?.authenticated)return window.RAF_AUTH_ROLE;lastUserId=user.id;const email=norm(user.email),role=email===COACH?'coach':'client';window.RAF_AUTH_ROLE={authenticated:true,email,role,isCoach:role==='coach',userId:user.id};hideGate();document.body.dataset.rafRole=role;authActions();document.dispatchEvent(new CustomEvent('raf-auth-ready',{detail:window.RAF_AUTH_ROLE}));return window.RAF_AUTH_ROLE}
function hideGate(){const g=$('#raf-supa-auth');if(g)g.style.display='none'}
async function boot(){const s=sb();if(!s){showGate();return}showGate();s.auth.onAuthStateChange((_e,session)=>{if(session?.user)applyUser(session.user);else applyUser(null)});const r=await s.auth.getSession();applyUser(r.data?.session?.user||null)}
window.RAF_AUTH_V3={boot,refresh:applyUser,logout:async()=>{const s=sb();if(s)await s.auth.signOut();clearLocal();location.hash='dashboard';location.reload()}};
boot();
})();